### ISSUE TITLE
Visual graph generation

### ISSUE THREAD

**Issue by azngeek** [winzou/StateMachineBundle#12]
Hello,

one thing i am always missing is something like a visual presentations of the states like this state diagram 

![Example](http://www.perl.com/pub/2004/09/23/graphics/final.jpg)

As i have some complex machines with 10+ states and therefore lots of transitions, this would help me to better understand and explain the machine to another person. Is there something which you evaluated? It could for example be used for automated document generation.

Here some sources as reference:
- http://martin-thoma.com/how-to-draw-a-finite-state-machine/
- http://www.tonyballantyne.com/graphs.html

Here is an example based on your graph

```
digraph finite_state_machine {
    rankdir=LR;
    size="8,5"

    node [shape = doublecircle]; new;
    node [shape = point ]; qi

    node [shape = circle];
    qi -> new;
    new  -> pending_review [ label = "create" ];
    pending_rewiew  -> awaiting_changes  [ label = "ask for changes" ];
    pending_review -> accepted [ label = "approve" ];
    awaiting_changes -> pending_review [ label = "submit review" ];
    rejected -> accepted [ label = "approve" ];
    accepted -> published [label = "publish"]
    accepted -> awaiting_changes  [ label = "ask for changes" ];
}

dot -Tpng gv-file.gv -o myFiniteStateMachine.png


```

![myfinitestatemachine](https://cloud.githubusercontent.com/assets/213429/7657671/0b997e1c-fb34-11e4-9c41-b58cbdf28dc6.png)

**Comment by winzou** [comment]
Hi,

It would be nice to have indeed! But this is not something I will do myself because of time.
If you already have something and want to push I would be more than happy to include it.

Thanks.

**Comment by MadMind** [comment]
@azngeek I'm not really good at bundle configurations, so I decided that a separate bundle would be easier to create :)

https://github.com/MadMind/StateMachineVisualizationBundle
Let me know if you have issues with it.

**Comment by khalid05** [comment]
Hello,

@MadMind instead of creating new bundle it will be better to create pull request. For my point of view to have bundle for it its not really relevant. I think it s better to have comand line to generate image.

**Comment by bpolaszek** [comment]
@khalid05 From my point of view, creating a dedicated bundle for that is relevant since it should mostly be useful only in development. 
To my eyes, no need to add extra dependencies to a production project.
