### ISSUE TITLE
Feature Request - Debug Command / List Callbacks

### ISSUE THREAD

**Issue by patrick-mcdougle** [winzou/StateMachineBundle#16]
I'd like to see a command line command that works a lot like the `debug:event-dispatcher` command, where you supply a graph, a transition, and optionally before/after and it lists all of the callbacks, in order, just like the event dispatcher lists the event listeners. Does anyone else have any thoughts about this? IMO this is useful if your state-machines are configured in more that one config file and you want to see everything in one place. Thoughts? Suggestions?

**Comment by winzou** [comment]
Hi @patrick-mcdougle 

Definitely an awesome idea! We could list callbacks but also states and transitions.
Would you be able to work on a PR to implement this?

**Comment by patrick-mcdougle** [comment]
@winzou You can see a start of this feature on my fork here: https://github.com/patrick-mcdougle/StateMachineBundle/tree/state-machine-command

Let me know if I should continue on this or open a PR right now. At this point it just takes one of the configuration keys (the one right under the winzou_state_machine root config key) and prints the states and transitions. I'm only going to be able to work on this on a limited basis so let me know how you'd like to continue.

**Comment by winzou** [comment]
Thanks for the initiative! Can you please open a PR so that we can easily see the diff and discuss about it?
