### ISSUE TITLE
Factory Question

### ISSUE THREAD

**Issue by patrick-mcdougle** [winzou/StateMachineBundle#17]
I've always wondered why we need to instantiate a different state machine for each instantiated domain object, can't we just instantiate one state machine per class, per graph? So instead of doing `$sm = $factory->get($object, 'graph-name')` for each domain object, you'd just do it once per CLASS and be able to pass instances of that class into the state machine asking it to transition the given object through a transition.

Here's the example of what I'm talking about:

    $foos = [new Foo(), new Foo(), new Foo()];
    $fooDefaultSM = $factory->get(current($foos), 'default') // First argument can also be a class name maybe?
    foreach ($foos as $foo) {
        if ($fooDefaultSM->can($foo, 'some-transition'))
            $fooDefaultSM->apply($foo, 'some-transition);
        }
    }

Under the current implementation, you need to instantiate one SM per iteration of the loop (3 of them). Under the proposed interface, you'd only need one SM total.

Thoughts? Am I missing something?

**Comment by winzou** [comment]
I don't see any advantage with your approach. At the end you still need to pass the object, so I find it more convenient to pass it at the factory level.

**Comment by patrick-mcdougle** [comment]
The advantage is not having to instantiate so many state machines.
