### ISSUE TITLE
How to create multiple graphs for the same entity

### ISSUE THREAD

**Issue by VaN-dev** [winzou/StateMachineBundle#22]
Can't find any doc about how to create multiple graphs for the same entity ? Tried to duplicate the conf from the graph property, but it throws a configuration error

**Comment by winzou** [comment]
Hi,
Can you post the configuration you have tried?

**Comment by moebaca** [comment]
I was wondering if this is possible and if it even makes sense? For example I have a process that can be of three different types. For Type A of the process I need to follow a set of transitions, for Type B I want it to follow a certain set of transitions, etc. This would be one table I suppose with a FK to a type table. How this library would map to that model though I do not know. For now I had to create three different tables for each process even though they are somewhat similar.. I had one guy busting me on the design though I don't think it looks too bad. Anyways, was just wondering if this guys question is feasible, sharing multiple graphs for one table.
