### ISSUE TITLE
trigger a service on initial state (aka entitie creation)

### ISSUE THREAD

**Issue by brunocombodo** [winzou/StateMachineBundle#34]
Hello,

I'd like to trigger a service on the initial state (aka entity creation),

I know that I can do it without the state machine, with an event listener, but I feel like the whole point of the state machine is to not use classical event listener, so it seems odd to me to have to use them on this first stage.

How should I do in this use case ? use an event, or use this (awesome) tool in a way that I didn't imagined?

Thanks by advance,
Bruno (a huge fan of winzou and his awesome symfony MOOC on openclassroom)

**Comment by winzou** [comment]
Hello,

You could have a transition from your initial state to your initial state (no change in state) and bind callbacks on this specific transition. What do you think?

**Comment by brunocombodo** [comment]
Hello, this solution seems good to me, I'll try it, thank you!
