### ISSUE TITLE
Symfony 4 Support

### ISSUE THREAD

**Issue by nickvanderzwet** [winzou/StateMachineBundle#42]
Does the latest version of this bundle 0.3.1 fully support Symfony 4?

I still got some autowiring issues:
```
Cannot autowire service "***\ProfileController": argument "$statemachine" of method "__construct()" references class "SM\Factory\Factory" but no such service exists. It cannot be auto-registered because it is from a different root namespace.
```
Maybe I have to include some configuration files?

**Comment by winzou** [comment]
Should be fixed here if you can have a look: https://github.com/winzou/StateMachineBundle/pull/43
Thanks
