### ISSUE TITLE
Exception when debugging  the state machine with the command

### ISSUE THREAD

**Issue by mikemix** [winzou/StateMachineBundle#47]
This line:

https://github.com/winzou/StateMachineBundle/blob/master/Command/winzouStateMachineDebugCommand.php#L143

throws an exception when a callback is set in the configuration. You assume the `$callback['on']` is an array, though it can be a scalar string. At least it is a string in any example out there.

**Comment by simonihmig** [comment]
I think this has been fixed by #50, so can be closed.
