### ISSUE TITLE
$this not in object context

### ISSUE THREAD

**Issue by Cathmor** [winzou/StateMachineBundle#49]
So was working with Sylius about a year ago really enjoyed your State Machine Bundle's implementation within in. I'm trying to incorporate it into my own project but am running into errors. I'm working with Symfony 4 and have an autowired service that's throwing a '$this not in object context' when I try to use it with the transition callback.  But when I use the same service in a controller or command or something, it works fine. Thoughts? Is there a config setting somewhere I need to set?

**Comment by aguidis** [comment]
I had the same error but I realized that I was using an old release (**0.3.1**) so first, check if you use a version above **0.4** and then make [your service public](https://symfony.com/blog/new-in-symfony-3-4-services-are-private-by-default) so the `ContainerAwareCallback` can fetch the service directly from the container.

**Comment by winzou** [comment]
@aguidis is right, you should try the version 0.4 that is compatible with Symfony 4. Let us know if it solves your issue. Thanks!

**Comment by Cathmor** [comment]
Yep, I using 0.3 on Symfony 4. Upgraded and all set. Thanks @aguidis and @winzou!
