### ISSUE TITLE
You have requested a non-existent parameter sylius.state_machine.class'

### ISSUE THREAD

**Issue by vasilvestre** [winzou/StateMachineBundle#51]
Hello,

I got this problem : `You have requested a non-existent parameter "sylius.state_machine.class".`

Using sylius 1.5 and symfony 4.3

**Comment by vvasiloi** [comment]
That's not an issue of this bundle.
And probably not an issue of Sylius either.
Check your configuration and bundles.

**Comment by vasilvestre** [comment]
I think it could be great to add an entry about the loading order of bundles :) (my problem)
