### ISSUE TITLE
Deprecation warning in Symfony 4.3

### ISSUE THREAD

**Issue by nmeirik** [winzou/StateMachineBundle#52]
In Symfony 4.3, the following deprecation warning is thrown:

```
The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "winzou_state_machine" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.
```

A fix for a similar issue can be seen here: https://github.com/FriendsOfSymfony/FOSMessageBundle/pull/348/commits/e0a05874077451043ec3682ce00406ba3f938036

**Comment by nmeirik** [comment]
https://github.com/winzou/StateMachineBundle/pull/54

**Comment by winzou** [comment]
Thanks for reporting!
