### ISSUE TITLE
Deprecation: winzouStateMachineDebugCommand extending ContainerAwareCommand

### ISSUE THREAD

**Issue by nmeirik** [winzou/StateMachineBundle#55]
```
The "winzou\Bundle\StateMachineBundle\Command\winzouStateMachineDebugCommand" class extends "Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand" that is deprecated since Symfony 4.2, use {@see Command} instead.
```

**Comment by nmeirik** [comment]
https://symfony.com/blog/new-in-symfony-4-2-important-deprecations#deprecated-containerawarecommand

**Comment by winzou** [comment]
Thanks for the heads up! Could you make a PR for this?

**Comment by nmeirik** [comment]
@winzou I had a quick look at the command. Based on the fact that it contains quite a lot of business logic and that I'm not using it myself I most likely won't be able to justify prioritizing it.

**Comment by winzou** [comment]
This has been fixed here: https://github.com/winzou/StateMachineBundle/pull/60
