### ISSUE TITLE
Symfony 5 support

### ISSUE THREAD

**Issue by Leobaillard** [winzou/StateMachineBundle#58]
One of the last pull requests apparently made the bundle compatible with Symfony 5.

Would it be possible to officially check if the bundle is compatible, and if so tag a version with an amended composer.json to allow Symfony 5?

Thanks!

**Comment by winzou** [comment]
Hi,

Sure! Can you take care of the check and, if so, open a PR to amend the `composer.json`? I would be happy to merge and tag.

Thanks!

**Comment by winzou** [comment]
Implemented here: https://github.com/winzou/StateMachineBundle/pull/60
