### ISSUE TITLE
how to cancel a transitions if a guard is not fulfilled?

### ISSUE THREAD

**Issue by richhl** [winzou/StateMachineBundle#8]
would you please give an example?....i think one needs to use a callback but not sure if there is a method for cancelling the on going transition....

**Comment by cawolf** [comment]
Hey, I'd like to pickup on this issue. I provided a PR adding guards for the state machine and would create  a solution for this issue as soon as this PR is merged to winzou/state-machine .

**Comment by richhl** [comment]
+1

___________________________

Richard C. Hidalgo Lorite
Director de Sistemas
ISI Argonauta, S.L.
C/Alcalá 196, apto. 13, 28028 Madrid
Telf: +34 91 356 85 08
http://www.argonauta.org

2016-09-17 22:29 GMT+02:00 Christian Alexander Wolf <
notifications@github.com>:

**Comment by winzou** [comment]
Will implement guard as per the mentionned PR. Closing this issue.

**Comment by winzou** [comment]
Thanks @richhl for the initial idea!
